<?php
$siteImagesUrl = "https://jrose.us/images/";
$emailReceiver = "joshuarosemobile@gmail.com";

$postsArr = array(
  0 => array(
    1 => "The Title Of An Article In Category 1",
    2 => "first-article",
    3 => "2022-04-22",
    5 => 1,
    6 => "2dengine.jpg",
    7 => "screenshot of a 2d game engine running",
    8 => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac feugiat sed lectus vestibulum mattis ullamcorper. Pharetra sit amet aliquam id diam maecenas ultricies mi. Ultricies tristique nulla aliquet enim tortor. Integer vitae justo eget magna fermentum iaculis. Egestas diam in arcu cursus euismod quis. Pellentesque adipiscing commodo elit at. Ac turpis egestas integer eget aliquet nibh praesent tristique. Ullamcorper a lacus vestibulum sed arcu. Morbi leo urna molestie at elementum. Vestibulum morbi blandit cursus risus at. Volutpat est velit egestas dui id. Est ultricies integer quis auctor elit sed. Ullamcorper sit amet risus nullam eget. Diam quam nulla porttitor massa id neque aliquam vestibulum. Nulla facilisi etiam dignissim diam quis enim.

    Adipiscing enim eu turpis egestas pretium aenean pharetra magna. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Eros in cursus turpis massa. Nec ultrices dui sapien eget mi. Ut sem viverra aliquet eget sit. Amet nisl purus in mollis nunc sed id semper. Pellentesque elit eget gravida cum. Sed enim ut sem viverra aliquet eget sit amet. Facilisis gravida neque convallis a. Morbi non arcu risus quis varius quam. Scelerisque eleifend donec pretium vulputate sapien nec. Eget nullam non nisi est sit amet. Elementum tempus egestas sed sed risus. Sit amet commodo nulla facilisi. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. In nisl nisi scelerisque eu ultrices vitae auctor eu.
    
    Mattis aliquam faucibus purus in. Pellentesque habitant morbi tristique senectus et. Cras pulvinar mattis nunc sed blandit. Est ante in nibh mauris cursus mattis molestie. Turpis egestas integer eget aliquet. Purus viverra accumsan in nisl nisi scelerisque eu ultrices. Habitant morbi tristique senectus et netus. Dignissim enim sit amet venenatis urna. Turpis in eu mi bibendum neque egestas congue quisque egestas. Venenatis cras sed felis eget. Semper quis lectus nulla at volutpat diam. Nisl purus in mollis nunc sed id. At auctor urna nunc id cursus metus. Bibendum est ultricies integer quis auctor. Ante in nibh mauris cursus mattis molestie a iaculis. Tempus urna et pharetra pharetra massa massa ultricies mi quis. Nunc mi ipsum faucibus vitae aliquet. Netus et malesuada fames ac turpis egestas sed. Tortor pretium viverra suspendisse potenti nullam ac tortor.
    
    Euismod in pellentesque massa placerat duis. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Viverra suspendisse potenti nullam ac tortor vitae. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Molestie a iaculis at erat pellentesque adipiscing. Metus aliquam eleifend mi in nulla. Quam lacus suspendisse faucibus interdum posuere lorem. Egestas congue quisque egestas diam. Posuere ac ut consequat semper viverra nam. Nec tincidunt praesent semper feugiat nibh. Tortor at risus viverra adipiscing at in tellus integer. In egestas erat imperdiet sed euismod nisi.
    
    Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Cras sed felis eget velit aliquet. Diam donec adipiscing tristique risus nec feugiat in. Fringilla urna porttitor rhoncus dolor. Aliquam nulla facilisi cras fermentum odio eu feugiat. In hendrerit gravida rutrum quisque non. Feugiat nisl pretium fusce id velit ut. Id porta nibh venenatis cras sed felis eget velit aliquet. Ut placerat orci nulla pellentesque dignissim enim sit. Est placerat in egestas erat imperdiet sed euismod nisi porta. Sed euismod nisi porta lorem. Pellentesque nec nam aliquam sem et tortor consequat id porta. Lacus vel facilisis volutpat est velit egestas dui id ornare. Porttitor eget dolor morbi non arcu risus quis varius quam. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Etiam dignissim diam quis enim lobortis. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Vitae tortor condimentum lacinia quis vel eros donec. At varius vel pharetra vel turpis.",
  ),
  1 => array(
    1 => "The Title Of An Article In Category 2",
    2 => "second-article",
    3 => "2022-09-15",
    4 => "2022-09-15",
    5 => 2,
    6 => "fireworks.jpg",
    7 => "fireworks",
    8 => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac feugiat sed lectus vestibulum mattis ullamcorper. Pharetra sit amet aliquam id diam maecenas ultricies mi. Ultricies tristique nulla aliquet enim tortor. Integer vitae justo eget magna fermentum iaculis. Egestas diam in arcu cursus euismod quis. Pellentesque adipiscing commodo elit at. Ac turpis egestas integer eget aliquet nibh praesent tristique. Ullamcorper a lacus vestibulum sed arcu. Morbi leo urna molestie at elementum. Vestibulum morbi blandit cursus risus at. Volutpat est velit egestas dui id. Est ultricies integer quis auctor elit sed. Ullamcorper sit amet risus nullam eget. Diam quam nulla porttitor massa id neque aliquam vestibulum. Nulla facilisi etiam dignissim diam quis enim.

    Adipiscing enim eu turpis egestas pretium aenean pharetra magna. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Eros in cursus turpis massa. Nec ultrices dui sapien eget mi. Ut sem viverra aliquet eget sit. Amet nisl purus in mollis nunc sed id semper. Pellentesque elit eget gravida cum. Sed enim ut sem viverra aliquet eget sit amet. Facilisis gravida neque convallis a. Morbi non arcu risus quis varius quam. Scelerisque eleifend donec pretium vulputate sapien nec. Eget nullam non nisi est sit amet. Elementum tempus egestas sed sed risus. Sit amet commodo nulla facilisi. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. In nisl nisi scelerisque eu ultrices vitae auctor eu.
    
    Mattis aliquam faucibus purus in. Pellentesque habitant morbi tristique senectus et. Cras pulvinar mattis nunc sed blandit. Est ante in nibh mauris cursus mattis molestie. Turpis egestas integer eget aliquet. Purus viverra accumsan in nisl nisi scelerisque eu ultrices. Habitant morbi tristique senectus et netus. Dignissim enim sit amet venenatis urna. Turpis in eu mi bibendum neque egestas congue quisque egestas. Venenatis cras sed felis eget. Semper quis lectus nulla at volutpat diam. Nisl purus in mollis nunc sed id. At auctor urna nunc id cursus metus. Bibendum est ultricies integer quis auctor. Ante in nibh mauris cursus mattis molestie a iaculis. Tempus urna et pharetra pharetra massa massa ultricies mi quis. Nunc mi ipsum faucibus vitae aliquet. Netus et malesuada fames ac turpis egestas sed. Tortor pretium viverra suspendisse potenti nullam ac tortor.
    
    Euismod in pellentesque massa placerat duis. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Viverra suspendisse potenti nullam ac tortor vitae. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Molestie a iaculis at erat pellentesque adipiscing. Metus aliquam eleifend mi in nulla. Quam lacus suspendisse faucibus interdum posuere lorem. Egestas congue quisque egestas diam. Posuere ac ut consequat semper viverra nam. Nec tincidunt praesent semper feugiat nibh. Tortor at risus viverra adipiscing at in tellus integer. In egestas erat imperdiet sed euismod nisi.
    
    Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Cras sed felis eget velit aliquet. Diam donec adipiscing tristique risus nec feugiat in. Fringilla urna porttitor rhoncus dolor. Aliquam nulla facilisi cras fermentum odio eu feugiat. In hendrerit gravida rutrum quisque non. Feugiat nisl pretium fusce id velit ut. Id porta nibh venenatis cras sed felis eget velit aliquet. Ut placerat orci nulla pellentesque dignissim enim sit. Est placerat in egestas erat imperdiet sed euismod nisi porta. Sed euismod nisi porta lorem. Pellentesque nec nam aliquam sem et tortor consequat id porta. Lacus vel facilisis volutpat est velit egestas dui id ornare. Porttitor eget dolor morbi non arcu risus quis varius quam. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Etiam dignissim diam quis enim lobortis. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Vitae tortor condimentum lacinia quis vel eros donec. At varius vel pharetra vel turpis.",
  ),


);

$aboutArr =  array(
  1 => "About Me",
  2 => "about-me",
  3 => "2022-01-01",
  4 => "2022-01-01",
  5 => 10,
  6 => "headshot.jpg",
  7 => "portrait of Dwayne Comacho",
  8 => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac feugiat sed lectus vestibulum mattis ullamcorper. Pharetra sit amet aliquam id diam maecenas ultricies mi. Ultricies tristique nulla aliquet enim tortor. Integer vitae justo eget magna fermentum iaculis. Egestas diam in arcu cursus euismod quis. Pellentesque adipiscing commodo elit at. Ac turpis egestas integer eget aliquet nibh praesent tristique. Ullamcorper a lacus vestibulum sed arcu. Morbi leo urna molestie at elementum. Vestibulum morbi blandit cursus risus at. Volutpat est velit egestas dui id. Est ultricies integer quis auctor elit sed. Ullamcorper sit amet risus nullam eget. Diam quam nulla porttitor massa id neque aliquam vestibulum. Nulla facilisi etiam dignissim diam quis enim.

  Adipiscing enim eu turpis egestas pretium aenean pharetra magna. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Eros in cursus turpis massa. Nec ultrices dui sapien eget mi. Ut sem viverra aliquet eget sit. Amet nisl purus in mollis nunc sed id semper. Pellentesque elit eget gravida cum. Sed enim ut sem viverra aliquet eget sit amet. Facilisis gravida neque convallis a. Morbi non arcu risus quis varius quam. Scelerisque eleifend donec pretium vulputate sapien nec. Eget nullam non nisi est sit amet. Elementum tempus egestas sed sed risus. Sit amet commodo nulla facilisi. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. In nisl nisi scelerisque eu ultrices vitae auctor eu.
  
  Mattis aliquam faucibus purus in. Pellentesque habitant morbi tristique senectus et. Cras pulvinar mattis nunc sed blandit. Est ante in nibh mauris cursus mattis molestie. Turpis egestas integer eget aliquet. Purus viverra accumsan in nisl nisi scelerisque eu ultrices. Habitant morbi tristique senectus et netus. Dignissim enim sit amet venenatis urna. Turpis in eu mi bibendum neque egestas congue quisque egestas. Venenatis cras sed felis eget. Semper quis lectus nulla at volutpat diam. Nisl purus in mollis nunc sed id. At auctor urna nunc id cursus metus. Bibendum est ultricies integer quis auctor. Ante in nibh mauris cursus mattis molestie a iaculis. Tempus urna et pharetra pharetra massa massa ultricies mi quis. Nunc mi ipsum faucibus vitae aliquet. Netus et malesuada fames ac turpis egestas sed. Tortor pretium viverra suspendisse potenti nullam ac tortor.
  
  Euismod in pellentesque massa placerat duis. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Viverra suspendisse potenti nullam ac tortor vitae. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Molestie a iaculis at erat pellentesque adipiscing. Metus aliquam eleifend mi in nulla. Quam lacus suspendisse faucibus interdum posuere lorem. Egestas congue quisque egestas diam. Posuere ac ut consequat semper viverra nam. Nec tincidunt praesent semper feugiat nibh. Tortor at risus viverra adipiscing at in tellus integer. In egestas erat imperdiet sed euismod nisi.
  
  Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Cras sed felis eget velit aliquet. Diam donec adipiscing tristique risus nec feugiat in. Fringilla urna porttitor rhoncus dolor. Aliquam nulla facilisi cras fermentum odio eu feugiat. In hendrerit gravida rutrum quisque non. Feugiat nisl pretium fusce id velit ut. Id porta nibh venenatis cras sed felis eget velit aliquet. Ut placerat orci nulla pellentesque dignissim enim sit. Est placerat in egestas erat imperdiet sed euismod nisi porta. Sed euismod nisi porta lorem. Pellentesque nec nam aliquam sem et tortor consequat id porta. Lacus vel facilisis volutpat est velit egestas dui id ornare. Porttitor eget dolor morbi non arcu risus quis varius quam. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Etiam dignissim diam quis enim lobortis. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Vitae tortor condimentum lacinia quis vel eros donec. At varius vel pharetra vel turpis.",
);
 ?>
